// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mzeutorvczucwocgdmfd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im16ZXV0b3J2Y3p1Y3dvY2dkbWZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3ODc1OTQsImV4cCI6MjA3MzM2MzU5NH0.ooIu2CazJzTmaWr_iuhSaRA_1v6H8UBYYE181J3jYuA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});